name: Validate Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v*.*.*
    types: [opened, synchronize]

env:
  NODE_VERSION: 22

jobs: # list of things to do
  validate-pull-request:
    name: Validate the pull request # job name (unique id)
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Check out
        uses: actions/checkout@v3

      - name: Install packages in root
        run: npm ci

      - name: Install packages in server
        working-directory: 'server'
        run: npm ci

      - name: Install packages in frontend
        working-directory: 'frontend'
        run: npm ci

      - name: Install packages in shared-lib
        working-directory: 'shared-lib'
        run: npm ci

      - name: Install packages in tools
        working-directory: 'tools'
        run: npm ci

      - name: Format (prettier) and Lint tools
        working-directory: '.'
        run: |
          npm run format:tools
          npm run lint:tools

      - name: Build tools
        working-directory: 'tools'
        run: npm run build

      - name: Format (prettier) and Lint shared
        working-directory: '.'
        run: |
          npm run format:shared
          npm run lint:shared

      - name: Build shared
        working-directory: 'shared-lib'
        run: npm run build

      - name: Format (prettier) and Lint frontend
        run: |
          npm run format:frontend
          npm run lint:frontend

      - name: Build frontend
        working-directory: 'frontend'
        run: npm run build

      - name: Format (prettier) and Lint server
        run: |
          npm run format:server
          npm run lint:server

      - name: Build and Test server
        working-directory: 'server'
        run: npm run test:server:ci
